//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotacionXYZ.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotacionXYZ;

public class Candidato implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public int id;

    public String nombre;

    public String apellido;

    public String nombrePartido;

    public Candidato()
    {
        this.nombre = "";
        this.apellido = "";
        this.nombrePartido = "";
    }

    public Candidato(int id, String nombre, String apellido, String nombrePartido)
    {
        this.id = id;
        this.nombre = nombre;
        this.apellido = apellido;
        this.nombrePartido = nombrePartido;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Candidato r = null;
        if(rhs instanceof Candidato)
        {
            r = (Candidato)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                return false;
            }
            if(this.nombre != r.nombre)
            {
                if(this.nombre == null || r.nombre == null || !this.nombre.equals(r.nombre))
                {
                    return false;
                }
            }
            if(this.apellido != r.apellido)
            {
                if(this.apellido == null || r.apellido == null || !this.apellido.equals(r.apellido))
                {
                    return false;
                }
            }
            if(this.nombrePartido != r.nombrePartido)
            {
                if(this.nombrePartido == null || r.nombrePartido == null || !this.nombrePartido.equals(r.nombrePartido))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::VotacionXYZ::Candidato");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, nombre);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, apellido);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, nombrePartido);
        return h_;
    }

    public Candidato clone()
    {
        Candidato c = null;
        try
        {
            c = (Candidato)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.id);
        ostr.writeString(this.nombre);
        ostr.writeString(this.apellido);
        ostr.writeString(this.nombrePartido);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readInt();
        this.nombre = istr.readString();
        this.apellido = istr.readString();
        this.nombrePartido = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Candidato v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Candidato ice_read(com.zeroc.Ice.InputStream istr)
    {
        Candidato v = new Candidato();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Candidato> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Candidato v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Candidato> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Candidato.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Candidato _nullMarshalValue = new Candidato();

    /** @hidden */
    public static final long serialVersionUID = -2059662010L;
}
