//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotacionXYZ.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotacionXYZ;

public class Ciudadano implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public String documento;

    public int mesaId;

    public Ciudadano()
    {
        this.documento = "";
    }

    public Ciudadano(String documento, int mesaId)
    {
        this.documento = documento;
        this.mesaId = mesaId;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Ciudadano r = null;
        if(rhs instanceof Ciudadano)
        {
            r = (Ciudadano)rhs;
        }

        if(r != null)
        {
            if(this.documento != r.documento)
            {
                if(this.documento == null || r.documento == null || !this.documento.equals(r.documento))
                {
                    return false;
                }
            }
            if(this.mesaId != r.mesaId)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::VotacionXYZ::Ciudadano");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, documento);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, mesaId);
        return h_;
    }

    public Ciudadano clone()
    {
        Ciudadano c = null;
        try
        {
            c = (Ciudadano)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.documento);
        ostr.writeInt(this.mesaId);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.documento = istr.readString();
        this.mesaId = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Ciudadano v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Ciudadano ice_read(com.zeroc.Ice.InputStream istr)
    {
        Ciudadano v = new Ciudadano();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Ciudadano> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Ciudadano v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Ciudadano> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Ciudadano.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Ciudadano _nullMarshalValue = new Ciudadano();

    /** @hidden */
    public static final long serialVersionUID = 1345834654L;
}
